name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r https://raw.githubusercontent.com/prov-a/prov-a.github.io/refs/heads/main/test/requirements.txt

    - name: Download test files
      run: |
        curl -o test_RDF_validation.py https://raw.githubusercontent.com/prov-a/prov-a.github.io/main/test/test_RDF/test_RDF_validation.py
        curl -o test_JSON_validation.py https://raw.githubusercontent.com/prov-a/prov-a.github.io/main/test/test_JSON/test_JSON_validation.py

    - name: Run tests for test_RDF_validation.py
      run: |
        pytest test_RDF_validation.py

    - name: Run tests for test_JSON_validation.py
      run: |
        pytest test_JSON_validation.py
